const dispensaries = [
    {
        src:require('./../assets/dispesaryImgs/lodge.jpg'),
        heading:'The Lodge',
        subHeading:'Outdoor and Indoor grown quality selections',
        offer:'20%',
        ratings:'4.9',
        time:'45 mins',
        cost:'$170q',
    },
    {
        src:require('./../assets/dispesaryImgs/first.png'),
        heading:'Light Shade',
        subHeading: "Colorado's prime",
        offer:'10%',
        ratings:'4.0',
        time:'55 mins',
        cost:'$250q',
    },
    {
        src:require('./../assets/dispesaryImgs/dab.jpg'),
        heading:'The Dab',
        subHeading:'Hardest Hittings Dabs in CO',
        offer:'25%',
        ratings:'3.9',
        time:'30 mins',
        cost:'$200q',
    },
    {
        src:require('./../assets/dispesaryImgs/silver.jpg'),
        heading:'Silver Stem',
        subHeading:'Silverthorn Maximum',
        offer:'10%',
        ratings:'3.2',
        time:'60 mins',
        cost:'$350q',
    },
    {
        src:require('./../assets/dispesaryImgs/orange.png'),
        heading:'Orange Kush',
        subHeading:'Kush For your Tush',
        offer:'5%',
        ratings:'5.0',
        time:'45 mins',
        cost:'$95q',
    },
    {
        src:require('./../assets/dispesaryImgs/psh.jpg'),
        heading:'Lightshade',
        subHeading:"Best shade you'll throw",
        offer:'25%',
        ratings:'3.8',
        time:'30 mins',
        cost:'$225q',
    },
    {
        src:require('./../assets/dispesaryImgs/silver.jpg'),
        heading:'Silver Stem',
        subHeading:'Silverthorn Maximum',
        offer:'10%',
        ratings:'3.2',
        time:'60 mins',
        cost:'$350q',
    },
    {
        src:require('./../assets/dispesaryImgs/lodge.jpg'),
        heading:'The Lodge',
        subHeading:'Outdoor and Indoor grown quality selections',
        offer:'20%',
        ratings:'4.9',
        time:'45 mins',
        cost:'$170q',
    }
    // }
    // {
    //     src:require('./../assets/restraunt/BrunosFriedChicken.jpg'),
    //     heading:'Brunos Fried Chicken',
    //     subHeading:'Fast food, Fried Chicken',
    //     offer:'25%',
    //     ratings:'4',
    //     time:'30 mins',
    //     cost:'$200',
    // },
    // {
    //     src:require('./../assets/restraunt/ShenaazsBakery.jpg'),
    //     heading:'Shehnaaz Bakery',
    //     subHeading:'Cakes, Desserts, Pastries',
    //     offer:'15%',
    //     ratings:'4.2',
    //     time:'50 mins',
    //     cost:'$125',
    // }
];

export default dispensaries;