const iconCarousel=[
    {
        title:'Flower',
        url:require('./../assets/icons/flower.jpg'),
        sellerUrl:''
    },
    {
        title:'Extracts',
        url:require('./../assets/icons/concentrate.jpg'),
        sellerUrl:''
    },
    {
        title:'Edibles',
        url:require('./../assets/icons/edibles.jpg'),
        sellerUrl:''
    },
    {
        title:'CBD',
        url:require('./../assets/icons/cbd.jpg'),
        sellerUrl:''
    },
    {
        title:'Drinks',
        url:require('./../assets/icons/beer.jpg'),
        sellerUrl:''
    },
    {
        title:'Equipment',
        url:require('./../assets/icons/equip.jpg'),
        sellerUrl:''
    },
    {
        title:'Merch',
        url:require('./../assets/icons/app.jpg'),
        sellerUrl:''
    },
];

export default iconCarousel;